name: covid_nlp
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
    - datashader
    - holoviews
    - umap-learn==0.4.0rc2
    - enstop
    - hdbscan
    - scispacy
    - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.4/en_core_sci_sm-0.2.4.tar.gz
    - top2vec
    - wordcloud
  - setuptools
  - wheel
  - git>=2.5  # for git worktree template updating
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - scikit-learn
  - joblib
  - nb_conda_kernels<2.2.0  # nb_conda_kernels issue #158
  - pandas
  - requests
  - pathlib
  - python=3.7
  - seaborn
  - bokeh
  - nltk
  - numba
